# version: "3.9"

services:
  mcp-agente-qa:
    build:
      context: .
      dockerfile: Dockerfile
    image: mcp-agente-qa:latest
    container_name: mcp-agente-qa
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "8400:8400"
    volumes:
      - ./documentacion_generada:/app/documentacion_generada
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.0001'
          memory: 20M